export interface Topic {
  name: string;
  icon: string;
}

// Defining a specific union type for subject keys ensures 
// Next.js routing and TypeScript work perfectly together.
export type SubjectKey = 'botany' | 'physics' | 'chemistry' | 'zoology';

export const SUBJECT_TOPICS: Record<SubjectKey, Topic[]> = {
  botany: [
    { name: "Algae (Phycology)", icon: "🌊" },
    { name: "Fungi (Mycology)", icon: "🍄" },
    { name: "Bryophytes", icon: "🌱" },
    { name: "Pteridophytes", icon: "🌿" },
    { name: "Gymnosperms", icon: "🌲" },
    { name: "Angiosperm Morphology", icon: "🌸" },
    { name: "Plant Anatomy", icon: "🔬" },
    { name: "Plant Taxonomy", icon: "🏷️" },
    { name: "Economic Botany", icon: "💰" },
    { name: "Plant Cell Structure", icon: "📦" },
    { name: "Plant Nucleus & Chromatin", icon: "🎯" },
    { name: "Mitosis & Meiosis", icon: "✂️" },
    { name: "Cell Cycle & CDKs", icon: "🔄" },
    { name: "Photosynthesis: Light Reaction", icon: "☀️" },
    { name: "Photosynthesis: Dark Reaction", icon: "🌙" },
    { name: "Respiration: Glycolysis", icon: "🔋" },
    { name: "Respiration: Krebs Cycle", icon: "🌀" },
    { name: "Plant Hormones (Auxins/GA)", icon: "🧪" },
    { name: "Nitrogen Metabolism", icon: "☁️" },
    { name: "Mendelian Genetics", icon: "🧬" },
    { name: "Post-Mendelian Genetics", icon: "🔗" },
    { name: "DNA Replication in Plants", icon: "🧬" },
    { name: "Transcription & RNA Processing", icon: "📝" },
    { name: "Translation & Protein Folding", icon: "🏗️" },
    { name: "Plant Biotechnology", icon: "⚙️" },
    { name: "Tissue Culture Techniques", icon: "🧪" },
    { name: "Plant Pathology (Diseases)", icon: "🍂" },
    { name: "Molecular Marker Systems", icon: "🔖" },
    { name: "Bioinformatics in Botany", icon: "💻" },
    { name: "Ecology & Succession", icon: "🌎" },
    { name: "Ethnobotany & Pharmacognosy", icon: "🏺" },
    { name: "Palynology (Pollen Study)", icon: "🌾" }
  ],
  physics: [
    { name: "Units & Dimensions", icon: "📏" },
    { name: "Vectors & Scalars", icon: "↗️" },
    { name: "Kinematics 1D & 2D", icon: "🏃" },
    { name: "Laws of Motion", icon: "🍎" },
    { name: "Work, Energy & Power", icon: "⚡" },
    { name: "Friction & Tension", icon: "🪢" },
    { name: "Center of Mass", icon: "⚖️" },
    { name: "Rotational Motion", icon: "🎡" },
    { name: "Gravitation", icon: "🪐" },
    { name: "Elasticity & Viscosity", icon: "💧" },
    { name: "Oscillations & SHM", icon: "⏳" },
    { name: "Waves & Sound", icon: "🔊" },
    { name: "Ray Optics", icon: "🔦" },
    { name: "Wave Optics (Interference)", icon: "🌈" },
    { name: "Thermodynamics: Laws", icon: "🔥" },
    { name: "Kinetic Theory of Gases", icon: "🎈" },
    { name: "Electrostatics", icon: "🌩️" },
    { name: "Capacitance", icon: "🔋" },
    { name: "Current Electricity", icon: "🔌" },
    { name: "Magnetism & Matter", icon: "🧲" },
    { name: "Electromagnetic Induction", icon: "🌀" },
    { name: "Alternating Current (AC)", icon: "〰️" },
    { name: "Electromagnetic Waves", icon: "📡" },
    { name: "Dual Nature of Matter", icon: "🌓" },
    { name: "Atomic Physics", icon: "⚛️" },
    { name: "Nuclear Physics", icon: "☢️" },
    { name: "Semiconductor Electronics", icon: "💾" },
    { name: "Solid State Physics", icon: "💎" },
    { name: "Quantum Mechanics", icon: "🌌" },
    { name: "Special Relativity", icon: "🚀" },
    { name: "Statistical Mechanics", icon: "📊" }
  ],
  chemistry: [
    { name: "Atomic Structure", icon: "⚛️" },
    { name: "Periodic Classification", icon: "📊" },
    { name: "Chemical Bonding", icon: "🔗" },
    { name: "States of Matter", icon: "🧊" },
    { name: "Chemical Thermodynamics", icon: "🔥" },
    { name: "Chemical Equilibrium", icon: "⚖️" },
    { name: "Ionic Equilibrium", icon: "💧" },
    { name: "Redox Reactions", icon: "🔄" },
    { name: "Hydrogen & S-Block", icon: "🔋" },
    { name: "P-Block Elements", icon: "💎" },
    { name: "GOC (Reaction Mechanisms)", icon: "🧪" },
    { name: "Isomerism", icon: "🧩" },
    { name: "Hydrocarbons", icon: "⛽" },
    { name: "D & F Block Elements", icon: "☢️" },
    { name: "Coordination Chemistry", icon: "🕸️" },
    { name: "Haloalkanes & Arenes", icon: "☣️" },
    { name: "Alcohols, Phenols & Ethers", icon: "🍷" },
    { name: "Aldehydes & Ketones", icon: "🧴" },
    { name: "Carboxylic Acids", icon: "🍋" },
    { name: "Chemical Kinetics", icon: "⏱️" },
    { name: "Surface Chemistry", icon: "🧼" },
    { name: "Electrochemistry", icon: "🔋" },
    { name: "Bio-Inorganic Chemistry", icon: "🧬" },
    { name: "Organometallic Compounds", icon: "⚙️" },
    { name: "Spectroscopy (NMR/IR)", icon: "🌈" },
    { name: "Polymers", icon: "🧶" },
    { name: "Biomolecules", icon: "🌾" },
    { name: "Analytical Chemistry", icon: "🔬" }
  ],
  zoology: [
    { name: "Animal Kingdom: Invertebrates", icon: "🐚" },
    { name: "Animal Kingdom: Vertebrates", icon: "🦴" },
    { name: "Structural Organization", icon: "🐾" },
    { name: "Digestion & Absorption", icon: "🍎" },
    { name: "Breathing & Respiration", icon: "🫁" },
    { name: "Body Fluids & Circulation", icon: "❤️" },
    { name: "Excretory Products", icon: "💧" },
    { name: "Locomotion & Movement", icon: "🏃" },
    { name: "Neural Control (Nervous System)", icon: "🧠" },
    { name: "Chemical Coordination (Hormones)", icon: "🧪" },
    { name: "Animal Reproduction", icon: "🐣" },
    { name: "Reproductive Health", icon: "🏥" },
    { name: "Principles of Inheritance", icon: "🧬" },
    { name: "Molecular Basis of Inheritance", icon: "🔬" },
    { name: "Evolutionary Biology", icon: "🐒" },
    { name: "Human Health & Disease", icon: "🦠" },
    { name: "Developmental Biology", icon: "🥚" },
    { name: "Immunology", icon: "🛡️" },
    { name: "Animal Physiology: Advanced", icon: "🐆" },
    { name: "Ethology (Animal Behavior)", icon: "🐺" },
    { name: "Entomology (Insects)", icon: "🐞" },
    { name: "Endocrinology", icon: "🩸" },
    { name: "Applied Zoology (Apiculture/Sericulture)", icon: "🐝" }
  ]
};